# Generated by Django 2.1.8 on 2020-06-01 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200601_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 6, 1, 15, 40, 33, 379208, tzinfo=utc)),
        ),
    ]
