# Generated by Django 2.1.8 on 2020-06-02 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200601_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 6, 2, 2, 20, 13, 687233, tzinfo=utc)),
        ),
    ]
